name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.9

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff
        run: uv run ruff check

      - name: Run mypy
        run: uv run mypy prosperity3bt

      - name: Update version
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: sed -i 's/version = "0.0.0"/version = "'"${GITHUB_REF##*/}"'"/g' pyproject.toml

      - name: Build
        run: uv build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: build

    environment:
      name: pypi
      url: https://pypi.org/p/prosperity3bt

    permissions:
      id-token: write

    steps:
      - name: Download all distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
